markdown: rdiscount
permalink: /:year/:month/:title/
url: http://cloudyr.github.io
author: the cloudyr project
name: the cloudyr project
description: R, cloud, cloud computing, aws, amazon, open science
